import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import type { ResumeData } from "@/lib/types/resume";
import { resumeToTxt } from "@/lib/export/txt";

/** Generate an editable, ATS-safe .docx for a resume. */
export async function resumeToDocxBuffer(data: ResumeData): Promise<Buffer> {
  const children: Paragraph[] = [];
  const p = data.personal ?? { fullName: "", jobTitle: "", email: "", phone: "", location: "", website: "", linkedin: "", github: "" };

  if (p.fullName) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 80 },
        children: [new TextRun({ text: p.fullName, bold: true, size: 44 })],
      }),
    );
  }
  if (p.jobTitle) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 120 },
        children: [new TextRun({ text: p.jobTitle, size: 26, color: "444444" })],
      }),
    );
  }

  const contact: string[] = [];
  if (p.location) contact.push(p.location);
  if (p.email) contact.push(p.email);
  if (p.phone) contact.push(p.phone);
  if (p.website) contact.push(p.website);
  if (p.linkedin) contact.push(p.linkedin);
  if (p.github) contact.push(p.github);
  if (contact.length) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
        children: [new TextRun({ text: contact.join("   ·   "), size: 20 })],
      }),
    );
  }

  for (const section of data.sections ?? []) {
    if (!section.visible) continue;
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 120 },
        children: [new TextRun({ text: section.title.toUpperCase(), bold: true, size: 22, color: "1f2937" })],
      }),
    );

    for (const item of section.items) {
      const headerParts: Array<{ text: string; bold?: boolean; italics?: boolean }> = [];
      if (item.heading) headerParts.push({ text: item.heading, bold: true });
      if (item.subheading) headerParts.push({ text: item.subheading, italics: true });
      const right = [item.date, item.location].filter(Boolean).join(" · ");
      if (headerParts.length) {
        children.push(
          new Paragraph({
            spacing: { before: 120, after: 40 },
            children: [
              ...headerParts.map((h) => new TextRun({ text: h.text, bold: h.bold, italics: h.italics, size: 23 })),
              ...(right ? [new TextRun({ text: `    ${right}`, size: 20, color: "666666" })] : []),
            ],
          }),
        );
      }
      if (item.description) {
        const clean = item.description.replace(/<[^>]*>/g, " ");
        for (const paragraph of clean.split(/\n+/)) {
          if (paragraph.trim()) {
            children.push(new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: paragraph.trim(), size: 22 })] }));
          }
        }
      }
      for (const bullet of item.bullets ?? []) {
        if (bullet.trim()) {
          children.push(
            new Paragraph({
              spacing: { after: 40 },
              indent: { left: 360, hanging: 180 },
              children: [new TextRun({ text: `• ${bullet.replace(/<[^>]*>/g, "").trim()}`, size: 22 })],
            }),
          );
        }
      }
      if (item.skills?.length) {
        children.push(new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: item.skills.join(", "), size: 22 })] }));
      }
    }
  }

  const doc = new Document({
    creator: "ResumeForge",
    title: p.fullName || "Resume",
    description: "Generated by ResumeForge — AI ATS resume builder",
    sections: [{ children }],
  });

  return Packer.toBuffer(doc);
}

export { resumeToTxt };
